# Generated by Django 4.1 on 2023-02-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("note_id", models.AutoField(primary_key=True, serialize=False)),
                ("note_title", models.CharField(max_length=100)),
                ("note_content", models.CharField(max_length=3000)),
                ("note_salt", models.CharField(max_length=100)),
                ("note_date", models.DateField()),
            ],
        ),
    ]
