# Generated by Django 4.1 on 2023-02-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Note",),
    ]
