# Generated by Django 4.1 on 2023-02-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="note", table=None,),
    ]
