# Generated by Django 4.1 on 2023-02-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_remove_note_n_user_remove_note_note_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="note_content",
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="note", name="note_date", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="note_salt",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="note_title",
            field=models.CharField(default="new diary", max_length=100),
        ),
    ]
