# Generated by Django 4.1 on 2023-02-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0008_note_note_iv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note", name="note_content", field=models.BinaryField(null=True),
        ),
    ]
