# Generated by Django 4.1 on 2023-02-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0009_alter_note_note_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="note_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="note_stared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="note_tag",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
