# Generated by Django 4.1 on 2023-02-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0010_note_note_deleted_note_note_stared_note_note_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="note_pwd_hint",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
