# Generated by Django 4.1 on 2023-02-05 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("note_id", models.AutoField(primary_key=True, serialize=False)),
                ("note_title", models.CharField(max_length=100)),
                ("note_content", models.CharField(max_length=3000)),
                ("note_salt", models.CharField(max_length=100)),
                ("note_date", models.DateField()),
                (
                    "n_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "note",},
        ),
    ]
