# Generated by Django 4.1 on 2023-02-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_note"),
    ]

    operations = [
        migrations.DeleteModel(name="Note",),
    ]
